name: Publish Wiki

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

jobs:
  publish-wiki:
    name: Publish Wiki

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs
